//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF.Dominio.Model.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comisiones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comisiones()
        {
            this.Pagos = new HashSet<Pagos>();
        }
    
        public int ComisionId { get; set; }
        public string NombreComision { get; set; }
        public decimal Monto { get; set; }
        public int ValorComision { get; set; }
        public string DescripcionComision { get; set; }
        public bool ComisionActiva { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pagos> Pagos { get; set; }
    }
}
