//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RF.Dominio.Model.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pagos
    {
        public int PagoId { get; set; }
        public int EmpleadoId { get; set; }
        public Nullable<int> ComisionId { get; set; }
        public System.DateTime FechaPago { get; set; }
        public Nullable<decimal> MontoPago { get; set; }
    
        public virtual Comisiones Comisiones { get; set; }
        public virtual Empleados Empleados { get; set; }
    }
}
